### ISSUE TITLE
Error: Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by harshitm1234** [ajv-validator/ajv#2443]
While build process using Craco Getting error **Cannot find module 'ajv/dist/compile/codegen'**

Below is the call stack generated By craco Build using node version **"v16.15.1"** and npm version **"8.11.0"**. This issue is reproducible once we delete node_modules and package-lock.json. Installing packages and using craco build will result in the above error. **ajv** is not used as dependency in the project.

Require stack:
- /node_modules/ajv-keywords/dist/definitions/typeof.js
- /node_modules/ajv-keywords/dist/keywords/typeof.js
- /node_modules/ajv-keywords/dist/keywords/index.js
- /node_modules/ajv-keywords/dist/index.js
- /node_modules/schema-utils/dist/validate.js
- /node_modules/schema-utils/dist/index.js
- /node_modules/mini-css-extract-plugin/dist/index.js
- /node_modules/react-scripts/config/webpack.config.js
- /node_modules/@craco/craco/dist/lib/cra.js
- /node_modules/@craco/craco/dist/scripts/build.js

<img width="1107" alt="Screenshot 2024-06-03 at 8 09 02 PM" src="https://github.com/ajv-validator/ajv/assets/36616432/95f7211e-774c-4209-9e91-9b0a923f2ae4">

**Comment by simoneconti** [comment]
Same issue, without craco.

`Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- C:\Users\xxx\git\yyy\zzz\node_modules\ajv-keywords\dist\definitions\typeof.js
- C:\Users\xxx\git\yyy\zzz\node_modules\ajv-keywords\dist\keywords\typeof.js
- C:\Users\xxx\git\yyy\zzz\node_modules\ajv-keywords\dist\keywords\index.js
- C:\Users\xxx\git\yyy\zzz\node_modules\ajv-keywords\dist\index.js
- C:\Users\xxx\git\yyy\zzz\node_modules\schema-utils\dist\validate.js
- C:\Users\xxx\git\yyy\zzz\node_modules\schema-utils\dist\index.js
- C:\Users\xxx\git\yyy\zzz\node_modules\webpack-dev-server\lib\Server.js
- C:\Users\xxx\git\yyy\zzz\node_modules\react-scripts\scripts\start.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zzz@1.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zzz@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2024-06-03T15_19_07_906Z-debug.log`

**Comment by Hsrf** [comment]
Also facing the same issue...

**Comment by chitru** [comment]
Project that was working suddenly starting giving this same error..

**Comment by achin178** [comment]
I also facing the same problem.
I can currently use: 
  npm install ajv --save-dev
as a workaround.

**Comment by intetm** [comment]
Seems like new version: 8.15.0 causes this bug. Our project stopped building however nothing had been changed.

**Comment by serheypast** [comment]
Has a similar issue

**Comment by scottdhicks** [comment]
> Seems like new version: 8.15.0 causes this bug. Our project stopped building however nothing had been changed.

8.14 started the issue for my project. We pinned to 8.13 for now to get things to work.

Any updates on a fix?

**Comment by madibaT** [comment]
We saw the same issue on our side. We had to pin to 8.14

**Comment by vivekkumar677** [comment]
I`m getting same issue

**Comment by viveksingh0072** [comment]
> I also facing the same problem. I can currently use: npm install ajv --save-dev as a workaround.

Worked, thanks

**Comment by venkataramanan-p** [comment]
same issue here...

**Comment by Rajesh6381** [comment]
> same issue here...

if you are use like this `npm install --force --legacy-peer-deps`,
try to use --force only `npm install --force`

**Comment by venkataramanan-p** [comment]
> > same issue here...
> 
> if you are use like this `npm install --legacy-peer-deps`, try to use --force `npm install --force`

Thanks mate!! That solved my issue. you saved my day!

**Comment by ashiqfury** [comment]
> > same issue here...
> 
> if you are use like this `npm install --legacy-peer-deps`, try to use --force `npm install --force`

Same issue here also. --force command helped me. Thanks for your valueable help.

**Comment by SaiPrasannaCdc** [comment]
Same issue in azure build pipeline, local is working fine

**Comment by ubudragon** [comment]
same in gcp cloud build

**Comment by TrejGun** [comment]
have that same with jest in one project and webpack in another project

**Comment by intetm** [comment]
Version **8.16** did NOT fix the issue

**Comment by TrejGun** [comment]
the problem is not in this module it is in ajv-keywords

![telegram-cloud-photo-size-1-5123292309750918233-y](https://github.com/ajv-validator/ajv/assets/185285/faa1fa63-2e6e-477e-a6b2-ce53d6cac74d)

ajv-keywords tries to get v8 but receives v6
but why so?
ajv is a peer dependency in ajv-keywords, it is not installed together 
and you all are seeing this package for the first time so it was installed by other package
so that means some package in the tree got updated and now the closest version in the three is v8

I have found a solution to add `"ajv": "8.8.2"` into my package.json and it worked in two completely different projects

**Comment by tomasmalio** [comment]
I modified my Dockerfile (`RUN npm install --legacy-peer-deps` to `RUN npm install --force`) and nothing happened.
I don't understand why this problem appears without calling it. I'm installing the "ajv": "8.8.2" as @TrejGun said if you install `"ajv": "8.8.2"` it works.
Thanks @TrejGun

**Comment by SaiPrasannaCdc** [comment]
> add `"ajv": "8.8.2"` into my package.json

this worked

**Comment by Alexander1987r** [comment]
Такая же проблема при запуске React.Как кто боролся подскажите?

**Comment by jasoniangreen** [comment]
Can everyone please try 8.16.0?

**Comment by jasoniangreen** [comment]
> We saw the same issue on our side. We had to pin to 8.14

Please update to 8.16.0 and let me know.

**Comment by intetm** [comment]
> > We saw the same issue on our side. We had to pin to 8.14
> 
> Please update to 8.16.0 and let me know.

I wrote above that version 8.16 did not help either.

**Comment by TrejGun** [comment]
> > We saw the same issue on our side. We had to pin to 8.14
> 
> Please update to 8.16.0 and let me know.

this does not help

**Comment by ShiiRochi** [comment]
Try freezing `ajv` to `~8.14.0` and `webpack` to `~5.82.1`. Playing only with `ajv` could not help.

**Comment by jasoniangreen** [comment]
Is it possible one of your other dependencies is pulling in the broken version (8.15.0) because 8.16.0 is identical to 8.14.0 apart from the version number ([see this diff tool](https://diff.intrinsic.com/ajv/8.14.0/8.16.0)).

If you look at your lock files do you see multiple versions of AJV mentioned?

**Comment by jasoniangreen** [comment]
> the problem is not in this module it is in ajv-keywords
> 
> ![telegram-cloud-photo-size-1-5123292309750918233-y](https://private-user-images.githubusercontent.com/185285/337626086-faa1fa63-2e6e-477e-a6b2-ce53d6cac74d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQzNzksIm5iZiI6MTcxNzg1NDA3OSwicGF0aCI6Ii8xODUyODUvMzM3NjI2MDg2LWZhYTFmYTYzLTJlNmUtNDc3ZS1hNmIyLWNlNTNkNmNhYzc0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzQxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWJlMWM2MzhkMmEzMzYyYmQwNThhMWIxMDA3ZjQ2ZTY4ZjhjOTAwNDQ1OTNlMmVlZjUyNGRkMzAyNmVlY2ZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CoXh5hMRg7F6mKD1jhyBo5pwtuYg1Sdt34ELG30sBdo)
> 
> ajv-keywords tries to get v8 but receives v6 but why so? ajv is a peer dependency in ajv-keywords, it is not installed together and you all are seeing this package for the first time so it was installed by other package so that means some package in the tree got updated and now the closest version in the three is v8
> 
> I have found a solution to add `"ajv": "8.8.2"` into my package.json and it worked in two completely different projects

I just saw this, maybe this issue is not related to the broken 8.15.0 release? I will look into it further. Maybe there's an issue that ajv-keywords is pointing at an [old version](https://github.com/ajv-validator/ajv-keywords/blob/master/package.json#L41) of AJV.

**Comment by jasoniangreen** [comment]
Oh and it would be much appreciated if someone can give me a simple example repo that reproduces the issue. With as few other dependencies as possible thanks!

**Comment by TrejGun** [comment]
try this one

https://github.com/Gemunion/nestjs-database

not the smallest one but I do not have another


```
git clone git@github.com:Gemunion/nestjs-database.git
cd nestjs-database
npm i
npm run bootstrap
cd apps/sequelize
npm start
```

the fix is in this commit

https://github.com/Gemunion/nestjs-database/commit/8c57a106efb70d19b520f45a25639615b8b2c12b

**Comment by toperrrrrrrr** [comment]
This fixed it for me, hope this helps:  

`npm install ajv@6 ajv-keywords@3 `

**Comment by pky92** [comment]
tried everything still now solved

**Comment by mumtyz** [comment]
> same issue here...

**Comment by TAPSIKATYAL** [comment]
We are facing same issue from 6th June 2024. We are using ajv 8.16.0 and ajv-keywords 5.1.0 version. Suddenly it stopped working when we were creating new build. Posting error stack to check the issue. Node version used 14.18.3.

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- \node_modules\ajv-keywords\dist\definitions\typeof.js
- \node_modules\ajv-keywords\dist\keywords\typeof.js
-\node_modules\ajv-keywords\dist\keywords\index.js
- \node_modules\ajv-keywords\dist\index.js
- \node_modules\schema-utils\dist\validate.js
- \node_modules\schema-utils\dist\index.js
- \node_modules\mini-css-extract-plugin\dist\index.js
-\node_modules\react-scripts\config\webpack.config.js
- \node_modules\react-scripts\scripts\build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (\node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
}

**Comment by laurentperroteau** [comment]
Add a newer version of `ajv` works for me too but it's cleaner to:

`npm install ajv --save-dev` and copying it in `override` in package.json

```json
  "devDependencies": {
    ...
    "ajv": "^8.16.0",
    ...
  },
  "overrides": {
    "ajv": "^8.16.0"
  },
```

This explicitly indicates you force your dependencies to use this version https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by Stefanmle** [comment]
I also get the same error, and I can´t even find "ajv" anywhere in my solution. Nothing with my build files or package.json has changed, it just stopped working from one day to another.

> react-scripts build

node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/definitions/typeof.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/keywords/typeof.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/keywords/index.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/index.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/schema-utils/dist/validate.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/schema-utils/dist/index.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/mini-css-extract-plugin/dist/index.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/react-scripts/config/webpack.config.js
- /home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/react-scripts/scripts/build.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/definitions/typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/definitions/typeof.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/keywords/typeof.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/keywords/index.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/ajv-keywords/dist/index.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/schema-utils/dist/validate.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/schema-utils/dist/index.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/mini-css-extract-plugin/dist/index.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/react-scripts/config/webpack.config.js',
    '/home/runner/work/mmk-dose-monitoring-web-admin-creative-tim-ts/mmk-dose-monitoring-web-admin-creative-tim-ts/node_modules/react-scripts/scripts/build.js'
  ]

**Comment by TAPSIKATYAL** [comment]
please check your package.lock.json. There you will find "ajv" package. Hopefully, it should help you.

**Comment by tapsi-capillary** [comment]
Just run this command "npm install ajv@8.16.0 ajv-keywords@5.1.0 schema-utils@4.2.0 --save-dev" . It will add package in package.json file and build it to see if any error comes.

**Comment by TAPSIKATYAL** [comment]
Just run this command "npm install ajv@8.16.0 ajv-keywords@5.1.0 schema-utils@4.2.0 --save-dev" . It will add package in package.json file and then it will point to 8.16v only, hopefully will not give error . But you can build it to see if any error comes.

**Comment by Stefanmle** [comment]
That worked great. Thank you :)

**Comment by jasoniangreen** [comment]
> Add a newer version of `ajv` works for me too but it's cleaner to:
> 
> `npm install ajv --save-dev` and copying it in `override` in package.json
> 
> ```json
>   "devDependencies": {
>     ...
>     "ajv": "^8.16.0",
>     ...
>   },
>   "overrides": {
>     "ajv": "^8.16.0"
>   },
> ```
> 
> This explicitly indicates you force your dependencies to use this version https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

The only explanation I can think of, if it is related to the broken release `8.15.0` is that there is some lag with these downstream dependencies and somewhere the wrong version is still being picked up. One of the examples shared had installed version 6 of AJV (very old) so that should have nothing to do with the bad release.

edit: Also I noted some older versions of node being used, it would be interesting, if possible, to try a newer version. AJV recently removed node 12 and 14 from our testing matrix. This doesn't mean we did anything specific to break on older versions of node, but that we're not focussed on them anymore.

**Comment by messyKassaye** [comment]
> Just run this command "npm install ajv@8.16.0 ajv-keywords@5.1.0 schema-utils@4.2.0 --save-dev" . It will add package in package.json file and then it will point to 8.16v only, hopefully will not give error . But you can build it to see if any error comes.

this works for me. Thanks

**Comment by yiyi1026** [comment]
I had to use `yarn install` first then `npm i` to make it work.

**Comment by jasoniangreen** [comment]
Has this issue died off? I'm wondering if there is a real issue that needs addressing or if it was just the nature of deep dependency chains that the bad version took a while to get out of the system (and in some cases people needed overrides to get there faster)?

**Comment by MashiGitCat** [comment]
> > same issue here...
> 
> if you are use like this `npm install --force --legacy-peer-deps`, try to use --force only `npm install --force`



> > same issue here...
> 
> if you are use like this `npm install --force --legacy-peer-deps`, try to use --force only `npm install --force`

Thanks ! It worked!

**Comment by RaSah673** [comment]
this "npm install ajv --save-dev" resolves the issue

**Comment by WalaceRamosdev** [comment]
> Eu também estou enfrentando o mesmo problema. Atualmente, posso usar: npm install ajv --save-dev como solução alternativa.

essa solução me atendeu bem...OBRIGADO !

**Comment by jasoniangreen** [comment]
I'm going to assume this is resolved and anyone needing to do `npm install ajv --save-dev` could also resolve by doing a clean npm install since all downstream dependencies should have the fixed version by now.

**Comment by lixingjuan** [comment]
If you use `npm update --legacy-peer-deps`, you can try `pnpm i`
It work for me

**Comment by ankit2821** [comment]
> This fixed it for me, hope this helps:
> 
> `npm install ajv@6 ajv-keywords@3 `

This worked for me.FYI I was working on a jest project and suddenly my working project stopped. Thanks!!

**Comment by neeraj542** [comment]
Use this to resolve this error:

`npm install ajv --save-dev`

**Comment by nima70** [comment]
> > same issue here...
> 
> if you are use like this `npm install --force --legacy-peer-deps`, try to use --force only `npm install --force`

Thanks. It solved my issue too.

**Comment by ritosilva** [comment]
> > > same issue here...
> > 
> > 
> > if you are use like this `npm install --force --legacy-peer-deps`, try to use --force only `npm install --force`
> 
> Thanks. It solved my issue too.

If I remove the --legacy-peer-deps I get other problems after npm start

It is a docker env that has been working for 2 years without a problem

**Comment by pppdns** [comment]
This solved the issue for me:
```
npm install ajv --save-dev
```

**Comment by mynameiskennith** [comment]
> I also facing the same problem. I can currently use: npm install ajv --save-dev as a workaround.

Worked. Thengs

**Comment by julianburr** [comment]
Ran in to this issue with the latest version (ajv@8.17.1), issue for us was that we were using `pnpm install --prod`, which seems to strip some of the ajv stuff. adding ajv as dependency instead of devDependency seems to fix it, even on the latest version.

**Comment by MarcosCnn** [comment]
> > `npm install ajv@6 ajv-keywords@3 `

MANO TU É FODA MANO VALEUUUU

**Comment by julianburr** [comment]
Ran in to this issue with the latest version (ajv@8.17.1), issue for us was that we were using `pnpm install --prod`, which seems to strip some of the ajv stuff. adding ajv as dependency instead of devDependency seems to fix it, even on the latest version.

**Comment by KristenDLR** [comment]
> npm install ajv@6 ajv-keywords@3

This worked for me as well.

**Comment by YASH-ai-bit** [comment]
you just need to run npm install ajv, thats it

**Comment by huynhnhutanhduy** [comment]
This worked for me. I hope it works for you.

```javascript
npm cache clean --force
npm install --force

**Comment by nitinkanade** [comment]
I recently encountered this same issue while working on my project, and after spending quite some time troubleshooting, I finally found a working solution.

In my case, the error `Cannot find module 'ajv/dist/compile/codegen'` was happening because certain internal modules of `ajv` were being referenced, but starting from `ajv@8.x`, the internal structure has changed significantly. Many modules that were previously accessible are now either private or have been completely restructured.

After analyzing the situation, I realized that some libraries (or even custom project code) were relying on internal paths like `'ajv/dist/compile/codegen'`, which are no longer available directly. Instead, the public API of `ajv` should be used wherever possible. If you are using an older dependency or code that relies on internal `ajv` files, you will need to either:

- Update those libraries to the latest version that is compatible with `ajv@8.x`, or
- Downgrade `ajv` to a 6.x or 7.x version (if immediate compatibility is needed and you cannot update the dependent libraries).

In my case, updating the dependent library and avoiding direct imports from internal paths fixed the issue.

I found a detailed explanation and the exact solution approach on this blog:  
👉 [https://blog.ni18.in/cannot-find-module-ajv-dist-compile-codegen/](https://blog.ni18.in/cannot-find-module-ajv-dist-compile-codegen/)

The blog clearly explains why the error happens and how to resolve it step-by-step. It was very helpful in understanding the root cause instead of just patching the symptom. Thanks to the author for putting together such a clear guide!

**Quick summary of what worked for me:**
- Ensure all dependent libraries using `ajv` are updated to versions compatible with `ajv@8`.
- Avoid accessing internal paths from `ajv`.
- If necessary, temporarily lock ajv version in `package.json` or use resolutions if you are using `npm` or `yarn`.

I hope this helps others who are facing the same confusing error.  
Thanks to the maintainers for continuously improving `ajv` — even though migrations can be a bit tricky, the overall improvements are very valuable!

**Comment by felicialatte** [comment]
I put this on my package.json for permanent fix:

```
"scripts": {
  "start": "set NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",
  "build": "set NODE_OPTIONS=--openssl-legacy-provider && react-scripts build",
  "test": "set NODE_OPTIONS=--openssl-legacy-provider && react-scripts test",
  "eject": "react-scripts eject"
}
```

and then put `import React from 'react'`; in my src/App.js

**Comment by pijus86** [comment]
This worked for me. I hope it works for you.
npm install --save-dev ajv@^7
then vs terminal
npm start

**Comment by diablo341** [comment]
> This worked for me. I hope it works for you. npm install --save-dev ajv@^7 then vs terminal npm start

I tried all of the above, except the post by nitinkanade, and only this solution worked.

**Comment by Recep-T** [comment]
Unfortunately I tried all above suggestions but not worked for me.

**Comment by Recep-T** [comment]
after spending 3 days I found the solution as  npm i ajv@latest --save-dev
